# Generated by Django 4.0 on 2022-02-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
